### ISSUE TITLE
De-crayon Nu's Licensing.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/NuGameEngine#57]
'Crayon' in the context of licensing - http://opensource.stackexchange.com/questions/1445/how-can-a-crayon-license-be-a-problem

It was suggested to have two licenses for the repo, one closed license for the assets, and an OSI one for the text / code.

Figure out a way to do this ASAP!

**Comment by borrrden** [comment]
As an example of how to achieve this goal, I suggest looking at the license page of [Font Awesome](https://fortawesome.github.io/Font-Awesome/license/)

**Comment by bryanedds** [comment]
Now that I have my commercial stuff working well enough from a separate repository, I think I'm going to go ahead and put this entire repo under MIT license.

Anyone have any further input (IE - is there a more permissive license I'm not aware of)?

**Comment by bryanedds** [comment]
Resolved with MIT license.
